# Generated by Django 5.2.1 on 2025-06-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
