# Generated by Django 5.2.1 on 2025-12-06 06:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_protection_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'În așteptare plată'), ('held', 'Fonduri în escrow'), ('released', 'Escrow eliberat'), ('disputed', 'Escrow în dispută')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('standard', 'Comandă magazin'), ('auction_win', 'Comandă licitație')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
