# Generated by Django 5.2.1 on 2025-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_buyer_protection_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_days_max',
            field=models.PositiveSmallIntegerField(default=0, help_text='Număr maxim de zile până la livrare.'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_days_min',
            field=models.PositiveSmallIntegerField(default=0, help_text='Număr minim de zile până la livrare (handling + curier).'),
        ),
    ]
