# Generated by Django 5.2.1 on 2026-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_days_max_order_shipping_days_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Creată'), ('awaiting_payment', 'În așteptare plată'), ('paid', 'Plătită'), ('shipped', 'Predată curierului'), ('in_transit', 'În tranzit'), ('delivered', 'Livrată'), ('completed', 'Finalizată'), ('refunded', 'Rambursată'), ('disputed', 'În dispută'), ('cancelled_by_buyer', 'Anulată de cumpărător'), ('cancelled_by_seller', 'Anulată de vânzător'), ('cancelled_by_admin', 'Anulată de Snobistic')], db_index=True, default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'În așteptare plată'), ('held', 'Fonduri în escrow'), ('released', 'Escrow eliberat'), ('disputed', 'Escrow în dispută'), ('refunded', 'Escrow rambursat')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('paid', 'Plătită'), ('failed', 'Eșuată'), ('cancelled', 'Anulată'), ('refunded', 'Rambursată'), ('chargeback', 'Chargeback')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Neexpediată'), ('shipped', 'Predată curierului'), ('in_transit', 'În tranzit'), ('delivered', 'Livrată'), ('returned', 'Returnată'), ('cancelled', 'Anulată')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins'), ('refunded', 'Rambursat')], default='pending', max_length=20),
        ),
    ]
