# Generated by Django 5.2.1 on 2025-06-12 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorite'},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='added_at',
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductAuthenticationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Dacă nu ești logat, lasă aici emailul la care primești certificatul', max_length=254)),
                ('image', models.ImageField(help_text='Încarcă o poză clară a produsului', upload_to='auth_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, help_text='Link către certificatul digital (populat după procesare)', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cerere autentificare produs',
                'verbose_name_plural': 'Cereri autentificare produse',
                'ordering': ['-created_at'],
            },
        ),
    ]
