# Generated by Django 5.2.1 on 2026-01-10 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
        ('catalog', '0027_delete_productmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verdict', models.CharField(choices=[('pending', 'În evaluare'), ('authentic', 'Autentic'), ('fake', 'Neautentic'), ('inconclusive', 'Neconcludent')], db_index=True, default='pending', max_length=16)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=60)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('certificate_file', models.FileField(blank=True, max_length=255, null=True, upload_to='certificates/')),
                ('certificate_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-verified_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='authimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='authrequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='authimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='brand_text',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='certificate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='model_text',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_requests', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='provider',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='verdict',
            field=models.CharField(choices=[('pending', 'În evaluare'), ('authentic', 'Autentic'), ('fake', 'Neautentic'), ('inconclusive', 'Neconcludent')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='authimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='auth_images/'),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='certificate_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('sent', 'Trimisă către provider'), ('success', 'Finalizată'), ('failed', 'Eșuată')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='authrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='authenticat_status_069816_idx'),
        ),
        migrations.AddIndex(
            model_name='authrequest',
            index=models.Index(fields=['provider', 'provider_reference'], name='authenticat_provide_72fe80_idx'),
        ),
        migrations.AddField(
            model_name='productauthentication',
            name='last_auth_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_to_products', to='authenticator.authrequest'),
        ),
        migrations.AddField(
            model_name='productauthentication',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authentication', to='catalog.product'),
        ),
    ]
