# Generated by Django 5.2.1 on 2026-01-10 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_productauthentication_alter_authimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
