# Generated by Django 5.2.1 on 2025-08-08 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiale',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('One Size', 'One Size'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('EU 35–46.5', 'EU 35–46.5'), ('FR 28–58', 'FR 28–58'), ('GB 2–30', 'GB 2–30'), ('IT 32–66', 'IT 32–66')], max_length=20)),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('shoulders', models.CharField(blank=True, max_length=50, verbose_name='Umeri')),
                ('bust', models.CharField(blank=True, max_length=50, verbose_name='Bust')),
                ('waist', models.CharField(blank=True, max_length=50, verbose_name='Talie')),
                ('hips', models.CharField(blank=True, max_length=50, verbose_name='Șold')),
                ('length', models.CharField(blank=True, max_length=50, verbose_name='Lungime')),
                ('sleeve', models.CharField(blank=True, max_length=50, verbose_name='Mâneca')),
                ('inseam', models.CharField(blank=True, max_length=50, verbose_name='Crac interior')),
                ('outseam', models.CharField(blank=True, max_length=50, verbose_name='Crac exterior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.material')),
                ('owner', models.ForeignKey(help_text='Cine a postat produsul', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
        ),
    ]
