# Generated by Django 5.2.1 on 2025-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_color_tag_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('ADULT', 'Adulți'), ('TEEN', 'Adolescenți')], default='ADULT', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('F', 'Femei'), ('M', 'Bărbați'), ('U', 'Unisex')], default='F', max_length=1),
        ),
    ]
