# Generated by Django 5.2.1 on 2025-11-26 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_is_default_billing_and_more'),
        ('catalog', '0004_alter_product_age_group_alter_product_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nu se afișează cumpărătorilor.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_start_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('FIXED', 'Vânzare la preț fix'), ('AUCTION', 'Licitație')], db_index=True, default='FIXED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_type'], name='catalog_pro_sale_ty_11e368_idx'),
        ),
    ]
