# Generated by Django 5.2.1 on 2025-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_auction_buy_now_price_product_auction_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_group',
        ),
        migrations.AddField(
            model_name='product',
            name='garment_type',
            field=models.CharField(blank=True, choices=[('TOP', 'Top / Bluză / Cămașă'), ('DRESS', 'Rochie'), ('BOTTOM', 'Pantaloni / Fustă / Jeans'), ('OUTERWEAR', 'Geacă / Palton'), ('SHOES', 'Încălțăminte'), ('ACCESSORY', 'Accesoriu')], db_index=True, default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
