# Generated by Django 5.2.1 on 2025-11-26 15:06

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_brand_remove_product_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(max_length=255, upload_to=catalog.models.product_main_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=catalog.models.product_extra_image_upload_to),
        ),
    ]
