# Generated by Django 5.2.1 on 2025-12-04 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_is_default_billing_and_more'),
        ('catalog', '0007_alter_product_main_image_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Branduri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand_other',
            field=models.CharField(blank=True, help_text='Dacă nu găsești brandul în listă, scrie-l aici.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category_other',
            field=models.CharField(blank=True, help_text='Dacă nu găsești subcategoria (ex: bluză, tricou), scrie-o aici.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_other_label',
            field=models.CharField(blank=True, help_text="Dacă ai ales 'Altă mărime', scrie mărimea exactă.", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW_TAG', 'Nou cu etichetă'), ('NEW_NO_TAG', 'Nou fără etichetă'), ('VERY_GOOD', 'Stare foarte bună'), ('GOOD', 'Stare bună')], default='VERY_GOOD', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('One Size', 'One Size'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('EU 35–46.5', 'EU 35–46.5'), ('FR 28–58', 'FR 28–58'), ('GB 2–30', 'GB 2–30'), ('IT 32–66', 'IT 32–66'), ('OTHER', 'Altă mărime')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_i_69e6f6_idx'),
        ),
    ]
