# Generated by Django 5.2.1 on 2025-12-04 21:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_brand_product_brand_other_product_category_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_visible_public',
            field=models.BooleanField(default=False, help_text='Dacă apare în filtrele/listările publice.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='dummy', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='auction_buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preț „Cumpără acum” (minim 10 RON).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='auction_reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nu se afișează cumpărătorilor. Minim 10 RON.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='auction_start_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preț de pornire minim 10 RON.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Preț minim 10 RON.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
    ]
