# Generated by Django 5.2.1 on 2025-12-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_brand_is_visible_public_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_size',
            field=models.CharField(blank=True, choices=[('S', 'Mic – plic mare'), ('M', 'Mediu – cutie de pantofi'), ('L', 'Mare – cutie pentru mutare')], db_index=True, help_text='Alege dimensiunea estimativă a coletului: Mic, Mediu sau Mare.', max_length=1),
        ),
    ]
