# Generated by Django 5.2.1 on 2025-12-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_package_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='size_group',
            field=models.CharField(blank=True, choices=[('CLOTH_ALPHA', 'Îmbrăcăminte (XXS–3XL)'), ('CLOTH_NUM', 'Îmbrăcăminte numerică (FR/GB/IT)'), ('SHOES', 'Încălțăminte (EU)'), ('ACCESSORIES', 'Accesorii / One size'), ('GENERIC', 'Generic / toate mărimile')], help_text='Controlează ce mărimi sunt disponibile pentru produsele din această categorie.', max_length=20),
        ),
    ]
