# Generated by Django 5.2.1 on 2025-12-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_role_buyer_profile_role_seller_and_more'),
        ('catalog', '0012_alter_category_name_alter_category_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_group',
            field=models.CharField(blank=True, choices=[('CLOTH_ALPHA', 'Îmbrăcăminte (XXS–3XL)'), ('CLOTH_NUM', 'Îmbrăcăminte numerică (FR/GB/IT)'), ('SHOES', 'Încălțăminte (EU)'), ('ACCESSORIES', 'Accesorii / One size'), ('GENERIC', 'Generic / toate mărimile')], help_text='Controlează ce mărimi sunt disponibile în mod implicit pentru produsele din această categorie.', max_length=20),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('size_group', models.CharField(blank=True, choices=[('CLOTH_ALPHA', 'Îmbrăcăminte (XXS–3XL)'), ('CLOTH_NUM', 'Îmbrăcăminte numerică (FR/GB/IT)'), ('SHOES', 'Încălțăminte (EU)'), ('ACCESSORIES', 'Accesorii / One size'), ('GENERIC', 'Generic / toate mărimile')], help_text='Dacă este setat, suprascrie grupa de mărimi a categoriei principale.', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Subcategorie',
                'verbose_name_plural': 'Subcategorii',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.subcategory'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='catalog_pro_subcate_777200_idx'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
