# Generated by Django 5.2.1 on 2025-12-06 07:51

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagine cover folosită pe homepage și în listările de categorii.', max_length=255, null=True, upload_to=catalog.models.category_cover_upload_to),
        ),
    ]
