# Generated by Django 5.2.1 on 2025-12-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_cover_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Dacă este setat, această subcategorie este un nivel 2 (ex: 'Geci bomber' sub 'Geci').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'parent', 'name')},
        ),
    ]
