# Generated by Django 5.2.1 on 2025-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_subcategory_unique_together_subcategory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Femei'), ('M', 'Bărbați'), ('U', 'Unisex')], help_text='Dacă este setat, subcategoria este afișată doar pentru produse cu acel gen (Femei / Bărbați / Unisex). Lăsată necompletată = valabilă pentru toate.', max_length=1),
        ),
    ]
