# Generated by Django 5.2.1 on 2025-12-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_subcategory_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_other',
        ),
    ]
