# Generated by Django 5.2.1 on 2025-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_product_category_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_pending_approval',
            field=models.BooleanField(default=False, help_text='Setat pentru brandurile noi propuse de utilizatori, până sunt aprobate de un admin.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'În așteptare'), ('APPROVED', 'Aprobat (validat)'), ('REJECTED', 'Respins'), ('PUBLISHED', 'Publicat'), ('SOLD', 'Vândut')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
