# Generated by Django 5.2.1 on 2025-12-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_brand_is_pending_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('DEADSTOCK', 'Deadstock / stoc nevândut'), ('PRELOVED', 'Preloved / second hand'), ('VINTAGE', 'Vintage'), ('UPCYCLED', 'Upcycled / recondiționat'), ('SUSTAINABLE_MATERIALS', 'Materiale sustenabile')], db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(help_text='Denumire afișată (poate coincide cu get_key_display).', max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Tag de sustenabilitate',
                'verbose_name_plural': 'Tag-uri de sustenabilitate',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.CharField(blank=True, choices=[('MAX_MARA_GROUP', 'Max Mara Group'), ('RALPH_LAUREN', 'Ralph Lauren'), ('COS', 'COS'), ('GANT', 'Gant'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('GUESS', 'Guess'), ('GAS', 'Gas'), ('PABLO', 'Pablo'), ('FAST_FASHION', 'Fast fashion'), ('OTHER', 'Alt brand / altele')], db_index=True, help_text='Gruparea brandului pentru filtre (Max Mara Group, Ralph Lauren, Fast fashion etc.).', max_length=40),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_fast_fashion',
            field=models.BooleanField(default=False, help_text='Setează True pentru branduri de tip fast fashion (Zara, H&M etc.).'),
        ),
        migrations.AddField(
            model_name='material',
            name='category_type',
            field=models.CharField(choices=[('CLOTHING', 'Îmbrăcăminte'), ('SHOES', 'Încălțăminte'), ('ACCESSORIES', 'Accesorii'), ('GENERIC', 'Generic / comun')], db_index=True, default='GENERIC', help_text='Tipul principal de produs pentru acest material.', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='is_sustainable',
            field=models.BooleanField(default=False, help_text='Bifează dacă materialul este considerat sustenabil (ex: bumbac organic, in, lyocell, poliester reciclat etc.).'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_color',
            field=models.ForeignKey(blank=True, help_text='Culoarea principală a articolului (folosită în filtre).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_products', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='real_color_name',
            field=models.CharField(blank=True, help_text='Nuanța reală (ex: Burgundy, Dusty Pink, Sage Green etc.).', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size_eu',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mărime încălțăminte EU (35–46.5, ex: 37.5).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_alpha',
            field=models.CharField(blank=True, help_text='Mărimea literă aproximativă (XXS–3XL) sau One Size.', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_none',
            field=models.BooleanField(default=False, help_text='Bifează dacă produsul NU are niciun element de sustenabilitate.'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='avg_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Greutatea medie a unui articol din această subcategorie (kg).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='co2_avoided_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CO₂ evitat per articol (kg).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='measurement_profile',
            field=models.CharField(blank=True, choices=[('TOP', 'Top / bluze / tricouri / cămăși / pulovere / sacouri'), ('DRESS', 'Rochii'), ('JUMPSUIT', 'Salopete'), ('PANTS', 'Pantaloni / blugi / leggings'), ('SKIRT', 'Fuste'), ('SHOES', 'Încălțăminte'), ('BAGS', 'Genți & rucsacuri'), ('BELTS', 'Curele'), ('JEWELRY', 'Bijuterii / accesorii mici'), ('ACCESSORY_GENERIC', 'Accesorii diverse')], help_text='Controlează ce măsurători în cm sunt obligatorii/opționale pentru produsele din această subcategorie (top, rochie, pantofi, genți etc.).', max_length=32),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='trees_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Număr de copaci echivalenți per articol.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_group',
            field=models.CharField(blank=True, choices=[('CLOTHING', 'Îmbrăcăminte'), ('SHOES', 'Încălțăminte'), ('ACCESSORIES', 'Accesorii'), ('GENERIC', 'Generic / toate mărimile')], help_text='Controlează ce tip de mărimi sunt disponibile în mod implicit pentru produsele din această categorie (îmbrăcăminte / încălțăminte / accesorii).', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_other_label',
            field=models.CharField(blank=True, help_text="Dacă ai ales 'Altă mărime', scrie mărimea exactă (ex: 38 IT, 29W).", max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='size_group',
            field=models.CharField(blank=True, choices=[('CLOTHING', 'Îmbrăcăminte'), ('SHOES', 'Încălțăminte'), ('ACCESSORIES', 'Accesorii'), ('GENERIC', 'Generic / toate mărimile')], help_text='Dacă este setat, suprascrie grupa de mărimi a categoriei principale.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_tags',
            field=models.ManyToManyField(blank=True, help_text='Deadstock, Preloved, Vintage, Upcycled, Materiale sustenabile.', related_name='products', to='catalog.sustainabilitytag'),
        ),
    ]
