# Generated by Django 5.2.1 on 2025-12-09 11:01

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_height_cm_profile_weight_kg'),
        ('catalog', '0020_sustainabilitytag_brand_group_brand_is_fast_fashion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bag_depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adâncimea genții în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bag_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Înălțimea genții în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bag_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lățimea genții în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='belt_length_total_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lungimea totală a curelei în cm (de la cap la cap).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='belt_length_usable_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lungimea utilă a curelei în cm (de la cataramă până la ultima gaură).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='belt_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lățimea curelei în cm.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='jewelry_chain_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lungimea lanțului / colierului în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='jewelry_drop_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lungimea „drop-ului” (cercei, pandantiv) în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='jewelry_pendant_size_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dimensiunea aproximativă a pandantivului în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_heel_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Înălțimea tocului în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_insole_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lungimea branțului (talpă interioară) în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_total_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Înălțimea totală a încălțămintei (de la talpă până sus) în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lățimea pantofului în cm (punctul cel mai lat).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_fr',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mărime numerică FR (28–58).', null=True, validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(58)]),
        ),
        migrations.AddField(
            model_name='product',
            name='size_gb',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mărime numerică GB (2–30).', null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='product',
            name='size_it',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mărime numerică IT (32–66).', null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(66)]),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lungimea maximă a baretei/șnurului în cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_non_returnable',
            field=models.BooleanField(default=False, help_text='Dacă este bifat, produsele din această subcategorie sunt marcate ca nereturnabile.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size_eu',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mărime încălțăminte EU (35–46.5, ex: 37.5).', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('35.0')), django.core.validators.MaxValueValidator(Decimal('46.5'))]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size_fr'], name='catalog_pro_size_fr_e20d11_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size_it'], name='catalog_pro_size_it_b6af53_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size_gb'], name='catalog_pro_size_gb_25efbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shoe_size_eu'], name='catalog_pro_shoe_si_24c137_idx'),
        ),
    ]
