# Generated by Django 5.2.1 on 2026-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_product_size_other_label_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_other_label',
            field=models.CharField(blank=True, help_text="Dacă mărimea nu este în listă, scrie-o aici (ex: 'W27 L32', 'Petite', 'Tall').", max_length=50),
        ),
    ]
