# Generated by Django 5.2.1 on 2026-01-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_size_other_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_other_label',
        ),
    ]
