# Generated by Django 5.2.1 on 2026-01-06 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_address_addr_non_billing_cannot_be_default_billing'),
        ('catalog', '0024_remove_product_size_other_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'În așteptare'), ('APPROVED', 'Aprobat (validat)'), ('REJECTED', 'Respins'), ('PUBLISHED', 'Publicat'), ('SOLD', 'Vândut')], db_index=True, default='PENDING', help_text='Workflow: PENDING (în așteptare) -> APPROVED (validat, dar nepublic) -> PUBLISHED (public/vizibil). REJECTED (respins). SOLD (vândut).', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['published_at'], name='catalog_pro_publish_1295c5_idx'),
        ),
    ]
