# Generated by Django 5.2.1 on 2026-01-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_product_published_at_alter_product_moderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_color',
            field=models.ForeignKey(blank=True, help_text='Culoarea produsului (SINGURA culoare, folosită în filtre și UI).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_products', to='catalog.color'),
        ),
    ]
