# Generated by Django 5.2.1 on 2026-01-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_product_base_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
