# Generated by Django 5.2.1 on 2025-12-06 12:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_buyer_protection_fee_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tracking_url_template', models.CharField(blank=True, help_text='Ex: https://tracking.courier.ro/?awb={tracking_number}', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='Numărul AWB.', max_length=100)),
                ('label_pdf', models.FileField(blank=True, help_text='PDF AWB (dacă îl salvezi de la un API extern).', upload_to='awb_labels/')),
                ('status', models.CharField(choices=[('pending', 'În pregătire'), ('label_generated', 'AWB generat'), ('handed', 'Predat curierului'), ('in_transit', 'În tranzit'), ('delivered', 'Livrat'), ('returned', 'Returnat')], db_index=True, default='label_generated', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Când a fost predat curierului.', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Când a fost livrat.', null=True)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Ultima actualizare de status.')),
                ('package_photo', models.ImageField(blank=True, help_text='Poză articol.', upload_to='shipments/package/')),
                ('parcel_photo', models.ImageField(blank=True, help_text='Poză colet închis.', upload_to='shipments/parcel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='logistics.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('seller', models.ForeignKey(help_text='Sellerul care trimite coletul.', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Național standard, Easybox, Local etc.', max_length=100)),
                ('min_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RON', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='logistics.courier')),
            ],
            options={
                'ordering': ['courier__name', 'base_price'],
            },
        ),
    ]
