# Generated by Django 5.2.1 on 2025-12-06 12:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cash_on_delivery',
            field=models.BooleanField(default=False, help_text='Dacă se folosește ramburs (COD).'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cod_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valoare ramburs (dacă cash_on_delivery=True).', max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID-ul expedierii în API-ul Curiera.', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True, help_text='URL către PDF AWB (dacă este hosted la Curiera).', max_length=500),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider',
            field=models.CharField(choices=[('curiera', 'Curiera'), ('manual', 'Introducere manuală')], db_index=True, default='curiera', help_text='De unde vine AWB-ul (Curiera sau manual).', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_name',
            field=models.CharField(blank=True, help_text='Ex: Standard, Easybox, SameDay etc. – cum le mapezi din Curiera.', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Link de tracking direct (dacă Curiera oferă unul).', max_length=500),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Greutate estimată colet (pentru tarife Curiera).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='courier',
            name='tracking_url_template',
            field=models.CharField(blank=True, help_text='Ex: https://tracking.couriera.ro/{tracking_number}', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_pdf',
            field=models.FileField(blank=True, help_text='PDF AWB salvat local (dacă alegi să îl descarci și să îl salvezi).', upload_to='awb_labels/'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(help_text='Numărul AWB (de la Curiera).', max_length=100),
        ),
    ]
