# Generated by Django 5.2.1 on 2025-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_shipment_cash_on_delivery_shipment_cod_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(default=3, help_text='Număr maxim de zile estimat de livrare pentru acest serviciu.'),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(default=1, help_text='Număr minim de zile estimat de livrare pentru acest serviciu.'),
        ),
    ]
