# Generated by Django 5.2.1 on 2026-01-02 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=160)),
                ('meta_description', models.CharField(blank=True, default='', max_length=320)),
                ('meta_robots', models.CharField(blank=True, default='', max_length=200)),
                ('canonical_path', models.CharField(blank=True, default='', help_text='Ex: /despre-noi/ (fără domeniu). Dacă e gol, folosim request.build_absolute_uri', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Snobistic', max_length=120)),
                ('default_meta_title', models.CharField(blank=True, default='Snobistic – Marketplace fashion autentic', max_length=160)),
                ('default_meta_description', models.CharField(blank=True, default='Snobistic este marketplace-ul de fashion autentic, cu magazin, licitații, autentificare produse și plăți în siguranță.', max_length=320)),
                ('default_meta_robots', models.CharField(blank=True, default='index, follow, max-snippet:-1, max-image-preview:large', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='support@snobistic.ro', max_length=254)),
                ('privacy_policy_version', models.CharField(blank=True, default='1.0', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_policy_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at'], name='core_contac_created_25856d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_processed', '-created_at'], name='core_contac_is_proc_b93660_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', '-created_at'], name='core_contac_email_6bffc4_idx'),
        ),
    ]
