# Generated by Django 5.2.1 on 2025-08-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='materials',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
