# Generated by Django 5.2.1 on 2025-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_materials'),
        ('catalog', '0003_brand_color_tag_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionimage',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='materials',
        ),
        migrations.AlterField(
            model_name='auction',
            name='min_price',
            field=models.DecimalField(decimal_places=2, help_text='Rezervă (preț minim acceptat)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='size',
            field=models.CharField(blank=True, choices=[('One Size', 'One Size'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('EU 35–46.5', 'EU 35–46.5'), ('FR 28–58', 'FR 28–58'), ('GB 2–30', 'GB 2–30'), ('IT 32–66', 'IT 32–66')], max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='catalog.material'),
        ),
    ]
