# Generated by Django 5.2.1 on 2025-12-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionimage_options_remove_auction_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='size',
            field=models.CharField(blank=True, choices=[('One Size', 'One Size'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('EU 35–46.5', 'EU 35–46.5'), ('FR 28–58', 'FR 28–58'), ('GB 2–30', 'GB 2–30'), ('IT 32–66', 'IT 32–66'), ('OTHER', 'Altă mărime')], max_length=20),
        ),
    ]
