# Generated by Django 5.2.1 on 2026-01-10 13:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_size'),
        ('catalog', '0027_delete_productmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'În așteptare plată'), ('PAID', 'Plătită'), ('EXPIRED', 'Expirată'), ('CANCELED', 'Anulată')], default='PENDING_PAYMENT', max_length=20)),
                ('payment_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NOT_AS_DESCRIBED', 'Produs neconform cu descrierea')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'În analiză'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins'), ('CLOSED', 'Închis')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='size',
        ),
        migrations.AddField(
            model_name='auction',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prețul curent (ultimul bid / start_price inițial).', max_digits=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='min_increment_percent',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='payment_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='payment_window_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rezervă (preț minim acceptat)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'În așteptare'), ('ACTIVE', 'Activă'), ('ENDED', 'Încheiată'), ('CANCELED', 'Anulată')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_winning_bid', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount', '-placed_at'], name='auctions_bi_auction_16e9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['user', '-placed_at'], name='auctions_bi_user_id_9878dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='auction',
            constraint=models.CheckConstraint(condition=models.Q(('reserve_price__isnull', True), ('reserve_price__gte', models.F('start_price')), _connector='OR'), name='auction_reserve_gte_start_or_null'),
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionreturnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='auctions.auctionorder'),
        ),
    ]
