# Generated by Django 5.2.1 on 2026-01-11 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('orders', '0005_order_cancelled_at_order_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='allow_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('ORDER', 'Order (buyer ↔ seller)'), ('SUPPORT', 'Support (user ↔ staff)')], db_index=True, default='SUPPORT', max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_conversations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='support_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['kind', 'last_updated'], name='messaging_c_kind_f063f4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['allow_staff', 'last_updated'], name='messaging_c_allow_s_b80ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='messaging_m_convers_118d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'sent_at'], name='messaging_m_sender__0f8c6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ORDER'), ('order__isnull', False), ('support_user__isnull', True)), models.Q(('kind', 'SUPPORT'), ('order__isnull', True), ('support_user__isnull', False)), _connector='OR'), name='conv_kind_requires_correct_link'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ORDER')), fields=('order',), name='uniq_order_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SUPPORT')), fields=('support_user',), name='uniq_support_conversation_per_user'),
        ),
    ]
