# Generated by Django 5.2.1 on 2026-01-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_message_attachment_messageattachment'),
        ('orders', '0005_order_cancelled_at_order_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversationreadstate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationreadstate',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversationreadstate',
            name='is_muted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversationreadstate',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationreadstate',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_closed', 'last_updated'], name='messaging_c_is_clos_22375b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['user', 'is_archived'], name='messaging_c_user_id_e58d19_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['user', 'is_muted'], name='messaging_c_user_id_feb7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['user', 'left_at'], name='messaging_c_user_id_9be8a2_idx'),
        ),
    ]
