# Generated by Django 5.2.1 on 2026-01-11 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_closed_at_conversation_closed_by_and_more'),
        ('orders', '0005_order_cancelled_at_order_completed_at_and_more'),
        ('support', '0003_alter_ticketmessage_options_alter_ticket_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='conv_kind_requires_correct_link',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_support_conversation_per_user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='support_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='support.ticket'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ORDER'), ('order__isnull', False), ('support_ticket__isnull', True), ('support_user__isnull', True)), models.Q(('kind', 'SUPPORT'), ('order__isnull', True), ('support_user__isnull', False)), _connector='OR'), name='conv_kind_requires_correct_link'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('support_ticket__isnull', True), ('kind', 'SUPPORT'), _connector='OR'), name='support_ticket_requires_support_kind'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SUPPORT'), ('support_ticket__isnull', True)), fields=('support_user',), name='uniq_general_support_conversation_per_user'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SUPPORT'), ('support_ticket__isnull', False)), fields=('support_ticket',), name='uniq_support_ticket_conversation'),
        ),
    ]
