# Generated by Django 5.2.1 on 2026-01-11 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='RON', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('TOP_UP', 'Încărcare'), ('WITHDRAW', 'Retragere'), ('ORDER_PAYMENT', 'Plată comandă'), ('REFUND', 'Refund'), ('SALE_PAYOUT', 'Încasare vânzare'), ('ADJUSTMENT', 'Ajustare')], db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit (+)'), ('DEBIT', 'Debit (-)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(blank=True, help_text='Ex: card, bank, internal, stripe_refund, etc.', max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID extern pentru idempotency (ex: Stripe payment_intent).', max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('iban', models.CharField(max_length=34)),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins'), ('PAID', 'Plătit')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='wallet_wall_currenc_81c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__83a8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['tx_type', 'created_at'], name='wallet_wall_tx_type_69d352_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('wallet', 'tx_type', 'external_id'), name='uniq_wallet_tx_type_external_id_when_present'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='wallet_with_status_8238f3_idx'),
        ),
    ]
