# Generated by Django 5.2.1 on 2025-12-06 12:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_buyer_protection_fee_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('product', 'Produse'), ('shipping', 'Transport'), ('commission', 'Comision platformă'), ('return', 'Retur')], db_index=True, default='product', max_length=20)),
                ('series', models.CharField(default='SNB', help_text='Serie factură (ex: SNB).', max_length=10)),
                ('number', models.CharField(blank=True, help_text='Număr factură (se generează automat dacă lipsește).', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Emisă'), ('canceled', 'Anulată')], db_index=True, default='draft', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Data emiterii facturii.')),
                ('due_date', models.DateField(blank=True, help_text='Scadență (opțional).', null=True)),
                ('currency', models.CharField(default='RON', max_length=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valoare fără TVA.', max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='TVA procent (ex: 19.00).', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valoare TVA.', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cu TVA.', max_digits=10)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF generat (opțional, pentru integrarea viitoare cu WeasyPrint / SmartBill).', null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order')),
                ('seller', models.ForeignKey(blank=True, help_text='Pentru comision platformă poți lăsa NULL sau seta un user intern.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total linie (cu TVA sau fără, în funcție de convenție).', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'issue_date'], name='invoices_in_invoice_c34345_idx'),
        ),
    ]
