# Generated by Django 5.2.1 on 2025-12-06 12:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('orders', '0003_order_buyer_protection_fee_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_invoice_c34345_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='series',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Număr factură (ex: SNB-2025-000123).', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data/ora emiterii facturii.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Data/ora plății facturii (dacă urmărim separat).', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('product', 'Produs'), ('shipping', 'Transport'), ('commission', 'Comision platformă'), ('return', 'Retur')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Baza de calcul (fără TVA).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Vânzătorul principal pentru această factură (dacă e cazul).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Emisă'), ('cancelled', 'Anulată')], db_index=True, default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='TVA în procente (ex: 19.00).', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoices_in_invoice_3d55b1_idx'),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
