# Generated by Django 5.2.1 on 2026-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoiceitem_invoice_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Număr factură (ex: SNB-2025-000123).', max_length=50, null=True, unique=True),
        ),
    ]
