# Generated by Django 5.2.1 on 2026-01-11 17:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_delete_productmaterial'),
        ('invoices', '0004_invoice_bill_to_address_invoice_bill_to_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='TVA default în procente (ex: 19.00). Liniile pot avea VAT diferit.', max_digits=5),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, help_text='Ordinea în factură (1..n).')),
                ('kind', models.CharField(choices=[('product', 'Produs'), ('shipping', 'Transport'), ('commission', 'Comision'), ('buyer_protection', 'Buyer protection'), ('discount', 'Discount'), ('adjustment', 'Ajustare'), ('other', 'Altele')], db_index=True, default='other', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('order_item_id', models.PositiveIntegerField(blank=True, help_text='ID linie comandă (dacă ai un model OrderItem; păstrăm id pentru decuplare).', null=True)),
                ('currency', models.CharField(default='RON', max_length=10)),
                ('unit_net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['invoice', 'position'], name='invoices_in_invoice_4be8aa_idx'), models.Index(fields=['kind'], name='invoices_in_kind_3cb382_idx'), models.Index(fields=['product'], name='invoices_in_product_ef546a_idx')],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'position'), name='uniq_invoice_line_position')],
            },
        ),
    ]
