# Generated by Django 5.2.1 on 2026-01-11 17:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_vat_percent_invoiceline'),
        ('orders', '0005_order_cancelled_at_order_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Storno / Credit note')], db_index=True, default='invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, help_text='Factura inițială (doar pentru storno/credit note).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Număr document (ex: SNB-20250111-000123). Se generează la emitere.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, help_text='Data/ora emiterii (setată la emitere, nu la creare).', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Emisă'), ('cancelled', 'Anulată')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='order_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['document_type'], name='invoices_in_documen_e55d72_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
    ]
