# Generated by Django 5.2.1 on 2025-12-06 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_days_max_order_shipping_days_min'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('order', 'Comandă'), ('return', 'Retur'), ('payment', 'Plată / escrow')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Dacă tichetul este despre o comandă anume, leagă-l aici.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='return_request',
            field=models.ForeignKey(blank=True, help_text='Dacă tichetul este despre un retur anume, leagă-l aici.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.returnrequest'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
