# Generated by Django 5.2.1 on 2026-01-11 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancelled_at_order_completed_at_and_more'),
        ('support', '0002_ticket_category_ticket_order_ticket_return_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nou'), ('in_progress', 'În lucru'), ('awaiting_user', 'Așteaptă răspuns utilizator'), ('resolved', 'Rezolvat'), ('rejected', 'Respins')], db_index=True, default='new', max_length=30),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['owner', 'status', 'updated_at'], name='support_tic_owner_i_7ac251_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='support_tic_status_08d7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
    ]
