# Generated by Django 5.2.1 on 2025-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('platiro', 'Plati.ro'), ('manual', 'Transfer bancar')], default='manual', max_length=20),
        ),
    ]
