# Generated by Django 5.2.1 on 2025-12-06 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_buyer_protection_fee_amount_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Încărcare'), ('withdraw', 'Retragere')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('wallet', 'Wallet intern')], default='stripe', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Suma totală plătită pentru comanda aceasta (în moneda de mai jos).', max_digits=10)),
                ('currency', models.CharField(default='RON', help_text='Moneda (ex: RON, EUR).', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('succeeded', 'Reușit'), ('failed', 'Eșuat'), ('canceled', 'Anulat')], db_index=True, default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, help_text='ID-ul Checkout Session din Stripe.', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Payment Intent ID din Stripe (dacă este disponibil).', max_length=255)),
                ('raw_response', models.JSONField(blank=True, help_text='Payload JSON Stripe (ultima versiune cunoscută).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
