# Generated by Django 5.2.1 on 2025-12-06 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_buyer_protection_fee_amount_and_more'),
        ('payments', '0002_alter_wallettransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Dacă plata a folosit un wallet intern, este legată aici.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Încărcare'), ('withdraw', 'Retragere'), ('order_payment', 'Plată comandă'), ('refund', 'Refund către client'), ('sale_payout', 'Încasare vânzare')], max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_wallet', models.BooleanField(default=True, help_text='Dacă True, suma se creditează în walletul userului.')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('succeeded', 'Reușit'), ('failed', 'Eșuat')], db_index=True, default='pending', max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, help_text='ID refund Stripe (dacă e cazul).', max_length=255)),
                ('reason', models.CharField(blank=True, help_text='Motivul refund-ului (intern/admin).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('user', models.ForeignKey(help_text='Cui îi facem refund (în mod normal buyer-ul).', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
