# Generated by Django 5.2.1 on 2025-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID tranzacție externă (ex: Stripe payment_intent).', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('wallet', 'Wallet intern'), ('cash', 'Numerar / Ramburs')], default='stripe', max_length=20),
        ),
    ]
