# Generated by Django 5.2.1 on 2026-01-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallettransaction_external_id_alter_payment_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='to_wallet',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Numerar / Ramburs'), ('wallet', 'Wallet')], default='stripe', max_length=20),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
