# Generated by Django 5.2.1 on 2026-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon_expires_at_coupon_max_discount_amount_and_more'),
        ('catalog', '0027_delete_productmaterial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cartitem_cart_product'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
