# Generated by Django 5.2.1 on 2025-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bust',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bust'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hips',
            field=models.CharField(blank=True, max_length=50, verbose_name='Șold'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inseam',
            field=models.CharField(blank=True, max_length=50, verbose_name='Crac interior'),
        ),
        migrations.AddField(
            model_name='profile',
            name='length',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lungime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='outseam',
            field=models.CharField(blank=True, max_length=50, verbose_name='Crac exterior'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shoulders',
            field=models.CharField(blank=True, max_length=50, verbose_name='Umeri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleeve',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mâneca'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist',
            field=models.CharField(blank=True, max_length=50, verbose_name='Talie'),
        ),
    ]
