# Generated by Django 5.2.1 on 2025-06-12 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activare cont'), ('password_reset', 'Resetare parolă'), ('email_change', 'Schimbare email')], default='activation', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'address_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='emailtoken',
            index=models.Index(fields=['token'], name='accounts_em_token_403c92_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtoken',
            index=models.Index(fields=['purpose'], name='accounts_em_purpose_1d9676_idx'),
        ),
    ]
