# Generated by Django 5.2.1 on 2025-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailtoken_options_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(default='e3b7a742a0584147b5afe8c2a0fef8be', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
