# Generated by Django 5.2.1 on 2025-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailtoken_created_at_alter_emailtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(default='08a8732967a94a30bd7e28f657f2d17b', max_length=128, unique=True),
        ),
    ]
