# Generated by Django 5.2.1 on 2025-12-04 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_is_default_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Cod unic folosit pentru programul de recomandări.', max_length=20, unique=True, verbose_name='cod referral'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='recomandat de'),
        ),
        migrations.AddField(
            model_name='profile',
            name='buyer_trust_score',
            field=models.PositiveSmallIntegerField(default=50, help_text='0–100, calculat din activitate, retururi, incidente etc.', verbose_name='scor seriozitate cumpărător'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC aprobat la'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Neînceput'), ('IN_REVIEW', 'În verificare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins')], default='NOT_STARTED', max_length=20, verbose_name='status KYC'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='accept_cod',
            field=models.BooleanField(default=False, help_text='Dacă este activ, pot exista comenzi cu plata la livrare (în condițiile de risc).', verbose_name='acceptă plata ramburs'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='allow_local_pickup',
            field=models.BooleanField(default=False, help_text='Permite livrarea în același oraș / ~20km sau întâlnire fizică.', verbose_name='permite livrare locală / ridicare personală'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='lifetime_sales_net',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volum vânzări folosit la determinarea nivelului (Amator/Rising/Top/VIP).', max_digits=12, verbose_name='volum vânzări net (RON)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='local_delivery_radius_km',
            field=models.PositiveSmallIntegerField(default=20, help_text='Folosită pentru livrări locale (Uber/Glovo/meet-up).', verbose_name='raza livrare locală (km)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='max_cod_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limită opțională pentru valoarea comenzilor ramburs.', max_digits=10, null=True, verbose_name='valoare maximă ramburs'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Comision aplicat vânzătorului (9 / 8 / 7 / 6 pentru Amator/Rising/Top/VIP).', max_digits=5, verbose_name='comision vânzător (%)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_level',
            field=models.CharField(choices=[('AMATOR', 'Amator Seller'), ('RISING', 'Rising Seller'), ('TOP', 'Top Seller'), ('VIP', 'VIP Seller')], default='AMATOR', help_text='Amator / Rising / Top / VIP – pe baza volumului de vânzări.', max_length=20, verbose_name='nivel vânzător'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_trust_score',
            field=models.PositiveSmallIntegerField(default=50, help_text='0–100, calculat din livrare, retururi din vina vânzătorului, rating etc.', verbose_name='scor seriozitate vânzător'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_type',
            field=models.CharField(choices=[('PRIVATE', 'Private seller (persoană fizică)'), ('PROFESSIONAL', 'Professional seller (persoană juridică)')], default='PRIVATE', max_length=20, verbose_name='tip vânzător'),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='code',
            field=models.CharField(help_text='Cod 3 litere (ex: ORA)', max_length=3),
        ),
    ]
