# Generated by Django 5.2.1 on 2025-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(default='36722f5d215d45dfa8a6b53ebc1b2698', max_length=128, unique=True),
        ),
    ]
