# Generated by Django 5.2.1 on 2025-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_referral_code_customuser_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_buyer',
            field=models.BooleanField(default=True, help_text='Dacă este activ, utilizatorul poate cumpăra produse pe Snobistic.', verbose_name='rol cumpărător activ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_seller',
            field=models.BooleanField(default=False, help_text='Dacă este activ, utilizatorul are drept de listare ca vânzător.', verbose_name='rol vânzător activ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_can_buy',
            field=models.BooleanField(default=True, help_text='Dacă este dezactivat, un cont de vânzător nu poate adăuga produse în coș.', verbose_name='vânzătorul poate cumpăra'),
        ),
    ]
