# Generated by Django 5.2.1 on 2025-12-08 14:34

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_contact_person',
            field=models.CharField(blank=True, help_text='Nume persoană de contact pentru firmă (ex: administrator, responsabil vânzări).', max_length=120, verbose_name='persoană de contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Denumirea comercială a companiei / PFA / SRL.', max_length=255, verbose_name='nume firmă'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefon de contact pentru firmă (dacă este diferit de telefonul personal).', max_length=128, region='RO', verbose_name='telefon firmă'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_reg_number',
            field=models.CharField(blank=True, help_text='Nr. registrul comerțului (ex: J05/123/2025).', max_length=50, verbose_name='număr înregistrare (RC)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True, help_text='Site-ul oficial al companiei (dacă există).', verbose_name='website firmă'),
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_CARD', 'Carte de identitate / Buletin'), ('PASSPORT', 'Pașaport'), ('DRIVING_LICENSE', 'Permis de conducere'), ('COMPANY_REG', 'Certificat înregistrare firmă / act constitutiv'), ('OTHER', 'Alt document')], max_length=32, verbose_name='tip document')),
                ('file', models.FileField(upload_to='kyc_documents/', verbose_name='fișier')),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('IN_REVIEW', 'În verificare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins')], default='PENDING', max_length=20, verbose_name='status')),
                ('is_primary', models.BooleanField(default=False, help_text='Dacă este bifat, acest document va fi folosit ca referință principală în badge-uri și afișări.', verbose_name='document principal')),
                ('reference_code', models.CharField(blank=True, help_text='Cod opțional folosit intern pentru tracking (ex: KYC-2025-0001).', max_length=64, verbose_name='cod referință intern')),
                ('notes', models.TextField(blank=True, help_text='Note pentru echipa de verificare (nu sunt vizibile userului).', verbose_name='note interne')),
                ('rejection_reason', models.TextField(blank=True, help_text='Completat atunci când statusul este Respins.', verbose_name='motiv respingere')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='încărcat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revizuit la')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiră la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL, verbose_name='utilizator')),
            ],
            options={
                'verbose_name': 'document KYC',
                'verbose_name_plural': 'documente KYC',
                'ordering': ['-created_at'],
            },
        ),
    ]
