# Generated by Django 5.2.1 on 2025-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_company_contact_person_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_address',
            field=models.CharField(blank=True, help_text='Adresă sediu social / punct de lucru pentru facturare.', max_length=255, verbose_name='adresă firmă'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vat_payer',
            field=models.BooleanField(default=False, help_text='Bifează dacă firma este înregistrată ca plătitoare de TVA.', verbose_name='plătitor TVA'),
        ),
    ]
