# Generated by Django 5.2.1 on 2025-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_company_address_profile_vat_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Folosește centimetri, ex: 170.', null=True, verbose_name='Înălțime (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Opțional; folosește kilograme, ex: 65.5.', max_digits=5, null=True, verbose_name='Greutate (kg)'),
        ),
    ]
