# Generated by Django 5.2.1 on 2026-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_height_cm_profile_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['expires_at'], name='accounts_tr_expires_269df0_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('user',), name='uniq_default_shipping_per_user'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('user',), name='uniq_default_billing_per_user'),
        ),
    ]
