# Generated by Django 5.2.1 on 2026-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_trusteddevice_token_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='note interne'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='reference_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='cod referință intern'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='motiv respingere'),
        ),
    ]
