# Generated by Django 5.2.1 on 2026-01-02 13:30

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_kycdocument_notes_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254, verbose_name='email nou')),
                ('token_hash', models.CharField(db_index=True, max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('CONFIRMED', 'Confirmat'), ('CANCELLED', 'Anulat'), ('EXPIRED', 'Expirat')], default='PENDING', max_length=12)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RO', verbose_name='telefon')),
                ('code_hash', models.CharField(max_length=512)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=6)),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('VERIFIED', 'Verificat'), ('FAILED', 'Eșuat'), ('EXPIRED', 'Expirat')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=12)),
                ('delta', models.SmallIntegerField()),
                ('score_after', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason', models.CharField(max_length=128)),
                ('ref_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Neverificat'), ('PENDING', 'În verificare'), ('VERIFIED', 'Verificat'), ('FAILED', 'Eșuat')], default='UNVERIFIED', max_length=12, verbose_name='status verificare telefon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='telefon verificat la'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de hash-uri pentru codurile de rezervă (nu codurile brute).'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='buyer_trust_score',
            field=models.PositiveSmallIntegerField(default=50, help_text='0–100, calculat din activitate, retururi, incidente etc.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='scor seriozitate cumpărător'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Comision aplicat vânzătorului (9 / 8 / 7 / 6 pentru Amator/Rising/Top/VIP).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='comision vânzător (%)'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_trust_score',
            field=models.PositiveSmallIntegerField(default=50, help_text='0–100, calculat din livrare, retururi din vina vânzătorului, rating etc.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='scor seriozitate vânzător'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_user_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('referral_code'), condition=models.Q(('referral_code', ''), _negated=True), name='uniq_user_referral_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='uniq_primary_kyc_doc_per_user'),
        ),
        migrations.AddField(
            model_name='emailchangerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneotpchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otp_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='ref_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='accounts_em_user_id_b59965_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['expires_at'], name='accounts_em_expires_a95e97_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailchangerequest',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('new_email'), condition=models.Q(('status', 'PENDING')), name='uniq_pending_email_change_new_email_ci'),
        ),
        migrations.AddIndex(
            model_name='phoneotpchallenge',
            index=models.Index(fields=['user', 'status', 'created_at'], name='accounts_ph_user_id_c614d1_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneotpchallenge',
            index=models.Index(fields=['expires_at'], name='accounts_ph_expires_f1d57f_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscoreevent',
            index=models.Index(fields=['user', 'subject', 'created_at'], name='accounts_tr_user_id_8043a0_idx'),
        ),
    ]
