# Generated by Django 5.2.1 on 2026-01-02 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_emailchangerequest_phoneotpchallenge_trustscoreevent_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Neînceput'), ('IN_REVIEW', 'În verificare'), ('NEEDS_MORE_INFO', 'Necesită informații suplimentare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.JSONField(blank=True, default=list, help_text='Note structurate (listă de obiecte): {ts, author_id(optional), note}.')),
                ('rejection_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff user care a făcut review-ul documentului (dacă există).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_document_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_iban',
            field=models.CharField(blank=True, help_text='IBAN folosit pentru facturare/încasări (dacă este cazul).', max_length=34, verbose_name='IBAN firmă'),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='source_app',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='source_event_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'În așteptare'), ('IN_REVIEW', 'În verificare'), ('NEEDS_MORE_INFO', 'Necesită informații suplimentare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Neînceput'), ('IN_REVIEW', 'În verificare'), ('NEEDS_MORE_INFO', 'Necesită informații suplimentare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins')], default='NOT_STARTED', max_length=20, verbose_name='status KYC'),
        ),
        migrations.AlterField(
            model_name='trustscoreevent',
            name='reason',
            field=models.CharField(choices=[('ORDER_CANCELLED', 'Order cancelled'), ('LATE_SHIPMENT', 'Late shipment'), ('CHARGEBACK', 'Chargeback'), ('DISPUTE_WON', 'Dispute won'), ('DISPUTE_LOST', 'Dispute lost'), ('REFUND_ISSUED', 'Refund issued'), ('RETURN_ABUSE', 'Return abuse'), ('KYC_APPROVED', 'KYC approved'), ('KYC_REJECTED', 'KYC rejected'), ('MANUAL_ADJUST', 'Manual adjustment')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='trustscoreevent',
            index=models.Index(fields=['source_app', 'source_event_id'], name='accounts_tr_source__2de3f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='uniq_pending_email_change_per_user'),
        ),
        migrations.AddConstraint(
            model_name='trustscoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_app', ''), _negated=True), models.Q(('source_event_id', ''), _negated=True)), fields=('source_app', 'source_event_id'), name='uniq_trust_event_source_pair'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff user care a făcut review-ul (dacă există).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.kycrequest'),
        ),
    ]
