# Generated by Django 5.2.1 on 2026-01-04 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_kycrequest_kycdocument_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('TERMS', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy'), ('COOKIES', 'Cookies Policy')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'doc_type', 'accepted_at'], name='accounts_le_user_id_99cdcd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'doc_type', 'version'), name='uniq_legal_acceptance_user_doc_ver')],
            },
        ),
    ]
