# Generated by Django 5.2.1 on 2026-01-04 09:26

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_legalacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='buyer_trust_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='scor seriozitate cumpărător'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresă firmă'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_contact_person',
            field=models.CharField(blank=True, max_length=120, verbose_name='persoană de contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN firmă'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nume firmă'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RO', verbose_name='telefon firmă'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_reg_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='număr înregistrare (RC)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='website firmă'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Înălțime (cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role_buyer',
            field=models.BooleanField(default=True, verbose_name='rol cumpărător activ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role_seller',
            field=models.BooleanField(default=False, verbose_name='rol vânzător activ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller_can_buy',
            field=models.BooleanField(default=True, verbose_name='vânzătorul poate cumpăra'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vat_payer',
            field=models.BooleanField(default=False, verbose_name='plătitor TVA'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Greutate (kg)'),
        ),
    ]
