# Generated by Django 5.2.1 on 2026-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_backup_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('ID_CARD', 'Carte de identitate / Buletin'), ('PASSPORT', 'Pașaport'), ('DRIVING_LICENSE', 'Permis de conducere'), ('PROOF_OF_ADDRESS', 'Dovadă adresă (utilități / extras bancar etc.)'), ('COMPANY_REG', 'Certificat înregistrare firmă / act constitutiv'), ('OTHER', 'Alt document')], max_length=32, verbose_name='tip document'),
        ),
    ]
