# Generated by Django 5.2.1 on 2026-01-04 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_kycdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buyer_bonus_2fa_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='buyer_bonus_kyc_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_bonus_2fa_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_bonus_kyc_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trustscoreevent',
            name='score_before',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
