# Generated by Django 5.2.1 on 2026-01-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_buyer_bonus_2fa_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Cod unic folosit pentru programul de recomandări.', max_length=20, unique=True, verbose_name='cod referral'),
        ),
        migrations.AlterField(
            model_name='trustscoreevent',
            name='reason',
            field=models.CharField(choices=[('ORDER_CANCELLED', 'Order cancelled'), ('LATE_SHIPMENT', 'Late shipment'), ('CHARGEBACK', 'Chargeback'), ('DISPUTE_WON', 'Dispute won'), ('DISPUTE_LOST', 'Dispute lost'), ('REFUND_ISSUED', 'Refund issued'), ('RETURN_ABUSE', 'Return abuse'), ('KYC_APPROVED', 'KYC approved'), ('KYC_REJECTED', 'KYC rejected'), ('SELLER_SALE_REGISTERED', 'Seller sale registered'), ('MANUAL_ADJUST', 'Manual adjustment')], max_length=32),
        ),
    ]
