# Generated by Django 5.2.1 on 2026-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('is_default_billing', False), ('is_billing', True), _connector='OR'), name='addr_default_billing_requires_billing'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('is_billing', True), ('is_default_billing', False), _connector='OR'), name='addr_non_billing_cannot_be_default_billing'),
        ),
    ]
