# Generated by Django 5.2.1 on 2026-01-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_address_addr_default_billing_requires_billing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='addr_non_billing_cannot_be_default_billing',
        ),
    ]
